[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "codeztest"
version = "0.1.0"
description = "Starter Python project"
authors = [{name = "codeztest authors"}]
requires-python = ">=3.8"

[project.scripts]
codeztest = "codeztest.cli:main"
